# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicationId', models.IntegerField(db_index=True, unique=True, verbose_name='ID')),
                ('applicationName', models.CharField(db_index=True, max_length=250, verbose_name='Navn')),
                ('applicationDescription', models.TextField(verbose_name='Beskrivelse')),
                ('applicationSystemOwner', models.CharField(db_index=True, max_length=250, verbose_name='Applikationsejer')),
            ],
        ),
        migrations.CreateModel(
            name='SupportDocumentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicationOneNoteId', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='OneNote ID')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='applicationlist.Application')),
            ],
        ),
    ]
