# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='applicationSystem',
            field=models.CharField(blank=True, db_index=True, max_length=150, verbose_name='System'),
        ),
        migrations.AddField(
            model_name='application',
            name='applicationSystemOwnerContact',
            field=models.CharField(blank=True, db_index=True, max_length=250, verbose_name='Kontakt'),
        ),
        migrations.AlterField(
            model_name='application',
            name='applicationName',
            field=models.CharField(db_index=True, max_length=250, verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='application',
            name='applicationSystemOwner',
            field=models.CharField(db_index=True, max_length=250, verbose_name='Ejer'),
        ),
        migrations.AlterField(
            model_name='supportdocumentation',
            name='applicationOneNoteId',
            field=models.CharField(blank=True, default=' ', max_length=250, null=True, verbose_name='OneNote ID'),
        ),
    ]
