# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-05-16 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicationlist', '0002_auto_20170918_1131'),
        ('applicationlist', '0003_auto_20180305_1345'),
    ]

    operations = [
    ]
